stages:
  data_ingestion:
    cmd: python sentiment_analysis/data_ingestion.py
    deps:
    - sentiment_analysis/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw
  data_preprocessing:
    cmd: python sentiment_analysis/data_preprocessing.py
    deps:
    - data/raw
    - sentiment_analysis/data_preprocessing.py
    outs:
    - data/processed
  feature_engineering:
    cmd: python sentiment_analysis/feature_engineering.py
    deps:
    - sentiment_analysis/feature_engineering.py
    params:
    - feature_engineering.max_features
    outs:
    - data/features
  model_building:
    cmd: python sentiment_analysis/model_building.py
    deps:
    - data/features
    - sentiment_analysis/model_building.py
    params:
    - model_building.learning_rate
    - model_building.n_estimators
    outs:
    - models/model.pkl
  model_evaluation:
    cmd: python sentiment_analysis/model_evaluation.py
    deps:
    - data/features
    - models/model.pkl
    - sentiment_analysis/model_evaluation.py
    metrics:
    - metrics.json
